language: android
jdk: 
 - oraclejdk8
# Use the Travis Container-Based Infrastructure

env:
  global:
    - ANDROID_API_LEVEL=28
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_TARGET=android-$ANDROID_API_LEVEL
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - android-$EMULATOR_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # Specify at least one system image
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build
  - ./gradlew build connectedAndroidTest --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
